version: '3'
services:
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: basics
      MYSQL_USER: bobbybrewer
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password