import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Button} from "@mui/material";
import {useEffect, useState} from "react";

const Home: NextPage = () => {
    const [data, setData] = useState<string | null>(null);
    const [isLoading, setLoading] = useState<boolean>(false)

    useEffect(() => {
        setLoading(true);
        fetch('/api/read-data')
            .then(res => {
                if (!res.ok) {
                    throw new Error("Network response was not ok");
                }
                return res.json();
            })
            .then(data => {
                setData(data.data); // Assuming your JSON structure includes a "payload" property
                setLoading(false);
            })
            .catch(error => {
                setData(error.toString());
                console.error('An error occurred:', error);
            });
    }, []);

    const brewABeer = (commands: any) => {
        // Here, you can make a fetch request to send messages and multiple commands to the OPC server
        fetch('/api/write-data', {
            method: 'POST',
            body: JSON.stringify({ messages: ['id', 'amount'], commands: commands }),
            headers: {
                'Content-Type': 'application/json'
            }
        });
        console.log("brewABeer called")
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1>Waesome webpage</h1>
                <div>Status of the machine: {data}</div>
                <div className={styles.buttons}>
                    <header>Choose a type of beer</header>
                    <Button variant="outlined" onClick={() => brewABeer([0, 1000])}>Pilsner</Button>
                    <Button variant="outlined" onClick={() => brewABeer([1, 1000])}>Wheat</Button>
                    <Button variant="outlined" onClick={() => brewABeer([2, 1000])}>IPA</Button>
                    <Button variant="outlined" onClick={() => brewABeer([3, 1000])}>Stout</Button>
                    <Button variant="outlined" onClick={() => brewABeer([4, 1000])}>Ale</Button>
                    <Button variant="outlined" onClick={() => brewABeer([5, 1000])}>Alcohol-free</Button>
                </div>
            </main>
        </div>
    )
}

export default Home
